### ISSUE TITLE
Permettre l'élévation de privilèges pour les montages cifs pour le pod agent

### ISSUE THREAD

**Issue by armandleopold** [qalita-io/helm#114]
```yaml
          securityContext:
            allowPrivilegeEscalation: true
            capabilities: {}
            privileged: true
```
