### ISSUE TITLE
Add Agent deployment by default

### ISSUE THREAD

**Issue by armandleopold** [qalita-io/helm#86]

**Comment by armandleopold** [comment]
````yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qalita-agent
  namespace: data-process-qalita
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-data-process-qalita-qalita-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      containers:
        - args:
            - agent
            - run
          command:
            - /app/qalita/main.py
          env:
            - name: QALITA_AGENT_NAME
              value: lovelace-agent
            - name: QALITA_AGENT_MODE
              value: worker
            - name: QALITA_AGENT_ENDPOINT
              value: https://api.qalita.data.curie.net/api/v1
            - name: QALITA_AGENT_TOKEN
              value: >-
***********************
          image: qalita/agent:1.4.1
          imagePullPolicy: Always
          name: container-0
          volumeMounts:
            - mountPath: /data
              name: vol-imqwx
            - mountPath: /root/.qalita/
              name: vol-imqwx
              subPath: ./qalita
      volumes:
        - name: vol-imqwx
          persistentVolumeClaim:
            claimName: dataqalita
````
